// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqmozswjkwbztaoxfeie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbW96c3dqa3dienRhb3hmZWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjQzODgsImV4cCI6MjA1NzM0MDM4OH0.B2yTHl18bbdZIdh2yH6OI5VT-NyHqHFtNoIczVNgN2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);